#import "@preview/grape-suite:3.1.0": exercise
#import exercise: project


#import "@preview/commute:0.3.0": node, arr, commutative-diagram

#import "@preview/ctheorems:1.1.3": *
#show: thmrules

#let question = thmbox("question", "Question", base_level: 0, fill: rgb("#155DFC33"))

#show: project.with(
    title: "Problem Set 5",
    university: "Tufts University",
    semester: "Fall 2025",
    seminar: "Math 065",
    faculty: "Prof. George McNinch",
    date: [due: 2025-10-08] 
)

#set enum(numbering: "a.")  


// operators
#let Hom = math.op("Hom")
#let Aut = math.op("Aut")
#let End = math.op("End")
#let Gal = math.op("Gal")
#let Mat = math.op("Mat")
#let GL = math.op("GL")
#let Inn = math.op("Inn")
#let Prop = math.op("Prop")
#let Aut = math.op("Aut")
#let Stab = math.op("Stab") 
#let Syl = math.op("Syl")

#let dirsum = [$plus.circle.big$]
#let Cl = math.op("Cl")

Let $R$ be a commutative ring (with identity...).


#question[
  + Let $M$ be an $R$-module, and let $I$ be an index set, and for $i   
    in I$, let $M_i subset.eq M$ for $i in I$ be an $R$-submodule.
    Write $sum_(i in I) M_i$ for the sum of submodules $M_i$. Thus
    $sum_(i in I) M_i$ coincides with the #emph[submodule generated by 
    the $M_i$].

    For a finitely supported function $(*)$ $f:I -> union.big_(i in I) M_i$ for which $f(j) in M_j$ for each $j in I$, note that
    $Sigma(f) = sum_(i in I) f(i)$ is a well-defined element of $M$.

    Prove that $sum_(i in I) M_i = { Sigma(f) | f "a finitely supported function satisfying" (*)}$

  + Assume that $M = sum_(i in I) M_i$ and that for a finitely   
    supported function $f$ satsifying $(*)$, we have $Sigma(f) = 0 => f(i) = 0$ for each $i in I.$ Prove that
    $M tilde.eq dirsum_(i in I) M_i.$


    One says in this case that $M$ is the #emph[internal direct sum] of
    the submodules $M_i$.

  + Let $X_1, X_2 subset.eq M$ be $R$-submodules. Suppose that 
    $M = X_1 + X_2$ and that $X_1 inter X_2 = 0.$ Prove that 
    $M tilde.eq X_1 plus.circle X_2.$ 

    One says in this case that $M$ is the #emph[internal direct sum] of $X_1$ and $X_2$.
]

#question[
  Let $I$ be an index set and let $M_i$ be and $R$-module for each $i in I$. 
  Let $M$ be the set of all functions $f:I -> union.big_(i in I) M_i$
  with such that $f(j) in M_j$ for each $j in I$. For $j in I$ let
  $ pi_j:M -> M_i "be the mapping" pi_j (f) = f(j). $

  Then $M$ is an $R$-module in a natural way, and $pi_j$ is an $R$-module homomorphism for each $j$.

  + Explain why $(M,pi_j)$ forms a #emph[product] of the $M_i$ in the 
    category $mod(R).$

    We usually write $M = product_(i in I) M_i$ for this $R$-module.

  + Suppose that $I$ is a finite set, let $(product_(i in I) M_i, pi_i)$
    be a product of the $M_i$, and let $(dirsum_(i in I) M_i,iota_i)$
    be a coproduct of the $M_i$. Show that there is an isomorphism
    $ Phi:dirsum_(i in I) M_i -> product_(i in I) M_i $
    of $R$-modules such that for $i,j in I$ we have $ pi_j compose Phi compose iota_i = cases(id "if" i =j,
    0 "otherwise.") $ 
]

#question[
  Let $M,N$ be $R$-modules. 
  Show that there is a short exact sequence
  $ 0 -> M ->^(iota_M) M plus.circle N->^(pi_N) N-> 0 $
  where $iota_M:M -> M plus.circle N$ and $iota_N:N -> M plus.circle M$ are the mappings defining the direct sum (coproduct) $M plus.circle N$, and $pi_M:M plus.circle N tilde.eq M times N -> M$ and  
  $pi_N:M plus.circle N tilde.eq M times N -> N$
  are the mappings defining the product $M times N$.
]

#question[
  Let $M,N$ be free $R$-modules. Thus there is some set $B$ and function $beta:B -> M$ such that $M$ is a free $R$-module $beta:B -> M$, and similarly for $N$.

  Prove that $M plus.circle N$ is a free $R$-module.
]

#question[
  Let $M$ be an $R$-module, let $I subset.eq R$ be an ideal.
  Assume that $a x = 0$ for each $a in I$ and each $x in M$.
  Show that $M$ has the structure of an $R slash I$-module.
] <question:R-slash-I-module>

#question[
  Let $I$ be an ideal of $R$ and let $M$ be an $R$-module.

  Let $I M$ be the $R$-submodule of $M$ generated by the set 
  $ {a x | a in I, x in M}. $

  + Prove that the $R$-module $M slash I M$ has the structure of an 
    $R slash I$-module. (Use @question:R-slash-I-module.)

  + If $M$ is a free $R$-module on $beta:B -> M$, 
    prove that $M slash I M$ is a free $R slash I$-module on 
    $ beta' = pi compose beta:B -> M slash I $ where $pi:M -> M slash I$ is the quotient morphism.


]