#import "@preview/grape-suite:3.1.0": exercise
#import exercise: project


#import "@preview/commute:0.3.0": node, arr, commutative-diagram

#import "@preview/ctheorems:1.1.3": *
#show: thmrules

#let question = thmbox("question", "Question", base_level: 0, fill: rgb("#155DFC33"))

#show: project.with(
    title: "Problem Set 6",
    university: "Tufts University",
    semester: "Fall 2025",
    seminar: "Math 245",
    faculty: "Prof. George McNinch",
    date: [due: 2025-10-15] 
)

#set enum(numbering: "a.")  


// operators
#let Hom = math.op("Hom")
#let Aut = math.op("Aut")
#let End = math.op("End")
#let Gal = math.op("Gal")
#let Mat = math.op("Mat")
#let GL = math.op("GL")
#let Inn = math.op("Inn")
#let Prop = math.op("Prop")
#let Aut = math.op("Aut")
#let Stab = math.op("Stab") 
#let Syl = math.op("Syl")

#let Cl = math.op("Cl")

Let $R$ be a commutative ring (with identity). We write $0$ for the  trivial $R$-module ${0}$.


#question[
  Consider a diagram $cal(A)$ of the form:
  $ #h(3mm) ... -> A_(i-1) ->^(d_(i-1)) A_i ->^(d_i) 
  A_(i+1) ->^(d_(i+1)) A_(i+2) -> ... $
  where for $i in ZZ$, $A_i$ is an $R$-module and $d_i:A_i -> A_(i+1)$ an $R$-module homomorphism.
  Then $cal(A)$ is said to be a #emph[complex] provided
  that $d^2 = 0$; i.e. that for each $i in ZZ$ we have
  $d_i compose d_(i-1) = 0.$ This implies that $im d_(i-1) subset.eq ker d_i.$

  And the complex $cal(A)$ is said to be #emph[exact] provided
  that $forall i in ZZ, im d_(i-1) = ker d_(i).$

  Let $cal(A)$ be a complex:

  + For $i in ZZ$ write $H^i (cal(A))$ for the $R$-module 
    $ker d_i slash im d_(i-1).$ Show that $cal(A)$ is exact if and only if $H^i (cal(A)) = 0$ for each $i in  ZZ$.

  + For $R$-modules $X,Y,Z$, we view a diagram
    $(suit.club) #h(3mm) 0 -> X ->^f Y ->^g Z -> 0$
    as a complex provided that $g compose f = 0$ by taking
    $ A_i = 0 #h(3mm) (i <= 0), A_1 = X, A_2 = Y, A_3 = Z, "and" A_j = 0 (4 <= j) $
    as well as $d_1 = f$, $d_2 = g$ and $d_j = 0$ for $j eq.not 1,2$.

    We say that the complex $(suit.club)$ is a #emph[short exact sequence] provided
    that $(suit.club)$ is an exact complex. 
    
    Prove that $(suit.club)$ is a short exact sequence if and only if
    (i) $f$ is injective, (ii) $ker(g) = im(f),$ and (iii) $g$ is surjective.

  + Let $phi:M -> N$ be an $R$-module homomorphism.
    Show that $ 0 -> ker phi ->^iota M ->^overline(pi) im phi -> 0 $
    is a short exact sequence, where $iota: ker phi -> M "and" pi:M -> im phi$  are the inclusion mapping and the quotient mapping, respectively.

]

#question[
  Let $M,N$ be $R$-modules. 
  Show that there is a short exact sequence
  $ 0 -> M ->^(iota_M) M plus.circle N->^(pi_N) N-> 0 $
  where $iota_M:M -> M plus.circle N$ and $iota_N:N -> M plus.circle M$ are the mappings for the direct sum (coproduct) $M plus.circle N$, and $pi_M:M plus.circle N tilde.eq M times N -> M$ and  
  $pi_N:M plus.circle N tilde.eq M times N -> N$
  are the mappings for the product $M times N$.
]

#question[
  For ideals $I,J subset.eq R$, the #highlight[product] of $I$ and $J$ is the ideal generated by $ {x  y | x in I, y in J}. $

  + Prove that $I J subset.eq I inter J$. 
  + If $P subset R$ is a _prime ideal_ and if $I J subset.eq P,$ prove
    that either $I subset.eq P$ or $J subset.eq P$.
]


#question[
  An element $a in R$ is said to be #highlight[nilpotent]
  if $exists N in NN, a^N =0.$

  For an ideal $I$ of $R$ and $n in NN$ we define the ideal $I^n$ inductively as follows:
  
  - $I^0 = R$, and 
  - for $n > 0$, $I^n = I dot I^(n-1)$

  An ideal $I$ is #highlight[nilpotent] if $exists N in NN, I^N = 0$.

  + If $a in R$ is nilpotent, prove that $1 - a b in R^times$ for every 
    $b in R$, where $R^times$ is the set of units of $R$.

  + Let $I = angle.l a_1,a_2,...,a_m angle.r$ for $a_i in R$ be a 
    finitely generated ideal. Prove that if $a_i$ is nilpotent for all $i$, then $I$ is a nilpotent ideal.
]

#question[
  Let $G$ be a group, and let $R[G]$ be the #highlight[monoid algebra] of $G$.
  Thus $R[G]$ is a free $R$-module with a basis ${e(g) | g in G}$
  and the multiplication satisfies $e(g) e(h) = e(g h)$ for $g,h in G$.

  + Prove that $ I = {sum_(g in G) a_g e(g) in R[G] mid(|) sum_(g in G) 
    a_g = 0} $
    is an 2-sided ideal of $R[G]$ and that the $R$-algebra
    $R[G] slash I$ is isomorphic to $R$. $I$ is called the #highlight[augmentation ideal] of $R[G]$.

  + Let $p$ be a prime number, let $G = angle.l sigma angle.r tilde.eq ZZ slash p ZZ$ be the 
    cyclic group of order $p$ (written multiplicatively), and let $FF_p = ZZ slash p ZZ$ be the field of $p$ elements.
    Show that the augmentation ideal $I$ of $FF_p [G]$ has an $FF_p$-basis
    consisting of ${ e(1) - e(sigma^i) | i=1,dots,p-1}$, and show
    that $I$ is a nilpotent ideal.
]

#question[
  Let $R[T]$ be the polynomial ring in a single variable over $R$.
  Recall for $f in R[T]$ that $angle.l f angle.r  = f dot R[T]$ denotes the principal ideal generated by $f$.
  + Let $ f = T^n + a_(n-1) T^(n-1) + ... + a_1 T  + a_0 "for" n in NN
    "and" a_i in R. $

    Prove that the quotient ring $R[T] slash f dot R[T]$ is a free $R$-module with a basis $ {overline(T^i) = T^i + f dot R[T] | 0 <= i <= n-1}. $
  + Prove that $ ZZ[T] slash angle.l 2T angle.r $
    is not a free $ZZ$-module. Describe this ring as a $ZZ$-module (i.e. as an abelian group).
]

#question[
  A ring $R$ is said to be a #highlight[local ring] if it has a unique
  maximal ideal. 

  + Prove that if $R$ is local with unique maximal ideal $M$, then 
    every element of $R backslash M$ is a unit in $R$.

  + Conversely, prove that if the set of non-units in $R$ forms an 
    ideal $M$, then $R$ is local with unique maximal ideal $M$.

  + Prove for a prime $p in ZZ$ that $R subset QQ$ defined by
    $ R = {a slash b | a,b in ZZ, b equiv.not 0 (mod p)} $
    is a local ring with unique maximal ideal $p R = angle.l p angle.r.$
]
