
#import "@preview/grape-suite:3.1.0": exercise
#import exercise: project


#show: project.with(
    title: [Assignment 3],
    seminar: [Math245],
    faculty: [George McNinch],
    semester: [Fall 2025, Tufts University],
    date: [due: 2025-09-22]
)

#import "@preview/ctheorems:1.1.3": *
#show: thmrules

// #let question = thmbox("question", "Question", base_level: 0, fill: rgb("#4d9bdb25"))
#let question = thmbox("question", "Question", base_level: 0, fill: rgb("#155DFC33"))


// operators
#let Hom = math.op("Hom")
#let Aut = math.op("Aut")
#let End = math.op("End")
#let Gal = math.op("Gal")

#let GL = math.op("GL")
#let SL = math.op("SL")
#let ZZn = n => $ZZ slash #n ZZ$
#let Inn= math.op("Inn")
#let Stab = math.op("Stab")

#set enum(numbering: "a.")  

#question[
  Let $A = ZZ times ZZ times ZZ$ and let $alpha,beta,gamma in A$.
  + Is the group $A slash angle.l alpha,beta angle.r$ finite for some 
    $alpha,beta$? Why or why not?
  + Give conditions under which the group 
    $A slash angle.l alpha,beta,gamma angle.r$ is finite?

  *Hint*: view the elements $alpha,beta,gamma$ as vectors in $QQ^3$. From linear algebra, we know that if these vectors are linearly independent, they form a basis for $QQ^3$. What does this say about the subgroup of $ZZ^3 = ZZ times ZZ times ZZ$ they generate? 
]

#question[
  For a group $G$ and elements $x,y in G$, the #highlight[commutator] of $x$ and $y$ is the element
  $ [x,y] = x dot y dot x^(-1) dot y^(-1). $
  + Let $G' = angle.l [x,y], x,y in G angle.r$ be the subgroup 
    generated by all commutators. Prove that $G'$ is a normal subgroup of $G$.
  + Prove that the quotient group $G slash G'$ is 
    #highlight[abelian (i.e. commutative)].
  + Suppose that $H$ is any abelian group and that $f:G -> H$ is a group 
    homomorphism. Prove that $forall x in G', f(x) = 1$; i.e. that $G' subset.eq ker f$. 
  + Deduce that there is a homomorphism 
    $overline(f):G slash G' -> H$ for which $overline(f) compose pi = f$ where $pi:G -> G slash G'$ is the quotient map. 

  Remark: $G slash G'$ is known  as the #highlight[abelianization] of $G$.
]

#question[
  Let $G$ be a finite $p$-group for some prime number $p$. 
  + Prove that $G$ has a central subgroup of order $p$.

    *Remark*: This result is required for the proof of Corollary 3.4.5 in the notes, so you shouldn't quote that result for the proof! You can use Theorem 3.4.4 though.

  + Prove that the commutator subgroup $G'$ (see previous 
    problem) is not equal to $G$.
]

#question[
  Let $Q$ be the subgroup of $GL_2(CC)$ generated by the matrices
  $ I = mat(0,-1;1,0), J = mat(i,0;0,-i). $
  + Prove that $Q$ is a group of order 8.
  + Prove that the center $Z$ of $Q$ has order $2$ and that 
    $ Q slash Z tilde.eq ZZ slash 2 ZZ times ZZ slash 2ZZ. $ 
  + Prove that $Z = Q'$ where $Q'$ is the commutator subgroup. 
]

#question[
  Let $F$ be any field and for $n in NN, n > 0$, let $G = GL_n (F)$.
  From linear algebra, we know that the determinant mapping 
  $ det:G -> F^times $
  is a group homomorphism, where $F^times = F - {0}$ is the multiplicative group of the field.

  Let $SL_n (F) = ker(det)$ be the subgroup ${g in GL_n (F) | det g = 1}$; it is known as the #highlight[special linear group].

  Prove that $GL_n (F) slash SL_n (F) tilde.eq F^times.$

]

#question[
  Let $n in NN$ and let $D = angle.l sigma, tau angle.r$ be the dihedral group of order $2n$ as in
  Example 2.6.6 in the notes. (So the order of $sigma$ is $n$.)

  + Suppose that $n = p$ is an odd prime number. Find a 2-Sylow subgroup $P$ of $D$.
  + Suppose that $n = 2p$ where $p$ is an odd prime number. Find a 2-Sylow subgroup $P$ of $D$ in this case. 
  + In the two cases above, decide whether or not $P$ is normal in $D$.
]