#import "@preview/grape-suite:3.1.0": exercise
#import exercise: project


#import "@preview/commute:0.3.0": node, arr, commutative-diagram

#import "@preview/ctheorems:1.1.3": *
#show: thmrules

#let problem = thmbox("problem", "Problem", base_level: 0, fill: rgb("#155DFC33"))

#show: project.with(
    title: "Problem Set week 11",
    university: "Tufts University",
    semester: "Fall 2025",
    seminar: "Math 245",
    faculty: "Prof. George McNinch",
    date: [due: 2025-11-19] 
)

#set enum(numbering: "a.")  


// operators
#let Hom = math.op("Hom")
#let Aut = math.op("Aut")
#let End = math.op("End")
#let Gal = math.op("Gal")
#let Mat = math.op("Mat")
#let GL = math.op("GL")
#let Inn = math.op("Inn")
#let Prop = math.op("Prop")
#let Aut = math.op("Aut")
#let Stab = math.op("Stab") 
#let Syl = math.op("Syl")
#let Mat = math.op("Mat")

#let mm = math.frak("m")

#let Cl = math.op("Cl")

#problem[
  Let $A$ be a ring and let $(suit.heart) #h(3mm) 0 -> X ->^j Y ->^psi Z -> 0$ be a 
  short exact sequence of $A$-modules.

  Prove that the following are equivalent:

  + There is an isomorphism $phi:X plus.o Z ->^tilde Y$
    such that $psi compose phi = pi_2$ and $phi^(-1) compose j = iota_1$ where
    $ pi_2:X plus.o Z -> Z "is" (x,z) |-> z, "and" iota_1:X -> X plus.o Z "is" x |-> (x,0).  $
  + There is a #highlight[section] to $psi$; i.e., there is an $A$-module 
    homomorphism $sigma:Z -> Y$ such that $ psi compose sigma = id_Z. $
  + There is a #highlight[retract] of $j$; i.e. there is an $A$-module 
    homomorphism $rho:Y -> X$ such that $ rho compose j = id_X. $

  The short exact sequence $(suit.heart)$ is said to be _split exact_ if it satisfies
  these equivalent conditions.
] <problem:split-sequence>

#problem[
  Let $ 0 -> X ->^iota Y ->^pi Z -> 0 $
  be a short exact sequence of $A$-modules.

  Prove that for an $A$-module $W$, the sequence
  $ (suit.club) #h(3mm) 0 -> Hom_A (W,X) ->^(f |-> iota compose f) Hom_A (W,Y) 
  ->^(g |-> pi compose g) Hom_A (W,Z) $
  is _exact_.

  NB. A sequence of $A$-modules and $A$-module homomorphisms is _exact_ if
  for each interior term $ dots S ->^f T ->^g Y  dots $ of the sequence,
  $ker g = im f.$ In the sequence $(suit.club)$, $Hom_A (P,Y)$ is not an interior term.

  *Remark:* The exactness of $(suit.club)$ for each short exact sequence  
  is often expressed by saying that the 
  functor $Hom_A (W,-)$ is _left-exact_.

  So your task is to check exactness of $(suit.club)$ at the interior terms $Hom_A (W,X)$ and $Hom_A (W,Y).$

]

#problem[
  An $A$-module $P$ is said to #highlight[projective] if 
  for every surjective homomorphism of $A$-modules $pi:M -> N$ and
  every $A$-module homomorphism $f:P -> N$, there is an $A$-module
  homomorphism $alpha:P -> M$ such that
  $pi compose alpha  f.$

  + Prove that any free $A$-module is projective.

  + Prove that a module $P$ is projective if and only if $P$ is a direct summand of a   
    free module; i.e. if there is a free $A$-module
    $F$ and an isomorphism of $A$-modules $F tilde.eq P plus.o Q$ for some $A$-module $Q$.
]

#problem[
  Prove that the following are equivalent:
  
  + $P$ is projective 
  + for every short exact sequence of $A$-modules $0 -> X -> Y ->Z -> 0$
    the sequence of $A$-modules
    $ 0 -> Hom_A (P,X) -> Hom_A (P,Y) -> Hom_A (P,Z) -> 0 $
    is exact. 

  *Remark:* Thus $P$ is projective if and only if the left-exact functor
  $Hom_A (P,-)$ is exact (in the sense that $Hom_A (P,-)$ carries short exact sequences to short exact sequences.).
]

#problem[
  Let $A$ be a commutative ring, let $B =A times A$, and let $pi:B -> A$ be the 
  projection ring homomorphism given by $pi(x,y) = x.$

  Using $pi$, we can view $A$ as a $B$-module. Prove that $A$ is a projective $B$-module that is not a free $B$-module.


]

#problem[
  Let $K$ be a field and let $a,b in K backslash {0,1}$ with $a eq.not b$.
  Let $q = T(T-a)(T-b) in K[T]$ and consider 
  the polynomial $f = S^2 - q in K[S,T].$

  You proved in the previous homework set that: 
  - $A = K[S,T] slash chevron.l f chevron.r$ is an integral domain. Write 
    $s,t$ for  the images of $S,T$ in the quotient ring $A$; 
    thus $s^2 = q(t) = t(t-a)(t-b)$ in $A$.
  - The map $K[T] -> k[t]$ for which $T |-> t$ is an isomorphism.
  - $A$ is a free $K[t]$-module on a basis ${1,s}$.

  + Define $N:A -> K[t]$ by the rule $N(alpha) = N(f + g s) = 
    f^2 - g^2 dot q(t)$ for $alpha = f + g s$ with $f,g in K[t]$. 

    Then $N$ is multiplicitive (i.e. it is a  monoid
    homomorphism) and $alpha in A$ is a unit in $A$ if and only if 
    $N(alpha) in K[T]^times = K^times.$ 

  + Write $mm = chevron.l s,t chevron.r$ for the ideal of $A$ generated by $s$ and $t$. 
    Show that the ideal $mm$ is not principal.

    *Hint:*
    Suppose to the contrary that $alpha = f + g dot s in A$ is a generator 
    for $mm$, for $f,g in k[t].$
    Then $alpha divides t = > N(alpha) divides t^2$. Now use a degree argument  
    to show that $g=0.$  

  + Show that $mm$ is a maximal ideal of $A$. 
  
  *Remark 1:* Essentially the same arguments show
  that the ideals 
  $ chevron.l s, t-a chevron.r "and" chevron.l s,t-b chevron.r $
  are maximal and not principal.

  *Remark 2:* The field of fractions $F = op("Frac")(A) = K(s,t)$ of $A$ is the _field of rational functions_ on the _elliptic curve_ over $K$
  defined by the cubic equation $S^2 = T(T-a)(T-b).$

  If we had consider instead the quadratic equation $S^2 = T(T-a)$, the
  analogous ideal $mm = chevron.l s,t chevron.r$ is princpal (!).
]

#problem[
  Keep the notations of the previous problem. We are going to show 
  that $mm$ is a projective $A$-module.

  + First, explain why the condition that $mm$ is not a principal ideal implies that
    $mm$ is not a free $A$-module.

  + Explain why $1 = u dot t  + v dot (t-a)(t-b)$ for some $u,v in k[t].$

  + Show for every $z in mm$ that $display(((t-a)(t-b)z) / s in A)$;
    note that _a priori_ $display(((t-a)(t-b)z) / s)$ is an element of
    the field of fractions of $A$.

  + Consider the surjective $A$-module homomorphism 
    $ pi:A^2 -> mm "given by" pi mat(x;y) = x s + y t. $
    Show that $sigma:mm -> A^2$ given by the rule
    $ sigma(z) = mat(v(t-a)(t-b)z slash s;u z) $ is a _section_ to $pi$
    (where $u,v$ are as in (b) above).
    
  + Conclude using problem (1) that $mm$ is isomorphic to a direct 
    summand of the free 
    module $A^2$. 

]





// Local Variables:
// typst-preview--master-file: "/home/george/Prof-VC/classes/AY2025-2026--2025-fa--Math245/assignments/2025-11-19--assignment11.typ"
// End:
